### ISSUE TITLE
Give server lib files less verbose names

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#126] opened 2019-12-12 17:45 UTC
It [was noted](https://github.com/elastic/kibana/pull/51403#discussion_r357111130) in a recent PR that we are calling files by fairly verbose names. We can probably do away with some of these longer naming conventions, as they were created to follow a paradigm that we have largely dropped from our codebase.

Examples are things like `elasticsearch_monitor_states_adapter`, associated `adapter_types` files. We could rename these to `monitor_states` and `types` respectively, and coupling the file name with its directory name should be descriptive enough to convey the same information.

**Comment by shahzad31** [comment] 2020-02-04 12:30
This is essentially duplicate of https://github.com/elastic/uptime/issues/131

**Closed by shahzad31** 2020-02-04 12:30 UTC
Labels: [zube]: Ready, technical debt
