### ISSUE TITLE
Click and drag on Uptime charts

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#109] opened 2019-11-12 15:28 UTC
**Is your feature request related to a problem? Please describe.**
This request comes out of https://github.com/elastic/uptime/issues/107. 

**Describe the solution you'd like**
Essentially users would like to click and drag to change the selected timespan in the application.

**Describe alternatives you've considered**
N/A

**Comment by shahzad31** [comment] 2020-02-07 09:57
duplicate of https://github.com/elastic/kibana/issues/46936

**Closed by shahzad31** 2020-02-07 09:57 UTC
Labels: [zube]: Backlog, discuss
